import { StyleSheet } from "react-native";
import { COLORS } from "./theme";

export const dashboardStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.white },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  iconButton: { padding: 4 },
  headerTitle: { fontSize: 18, fontWeight: "bold", color: COLORS.black },
  container: { padding: 24, paddingBottom: 40 },

  // Estilos da nova linha de cabeçalho das avaliações
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: 32,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.black,
    marginBottom: 4,
  },
  sectionSubtitleWrapper: {
    fontSize: 14,
    color: COLORS.darkBrown,
  },
  sectionSubtitle: { fontSize: 14, color: COLORS.darkBrown, marginBottom: 16 },

  averageBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F9F9F9",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  averageText: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.black,
  },

  highlightsGrid: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },
  highlightCard: {
    width: 100,
    height: 100,
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
    backgroundColor: "#eee",
  },
  highlightImage: { width: "100%", height: "100%" },
  deleteButton: {
    position: "absolute",
    top: 6,
    right: 6,
    backgroundColor: "rgba(0,0,0,0.6)",
    padding: 6,
    borderRadius: 20,
  },
  addHighlightButton: {
    width: 100,
    height: 100,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.mediumBrown,
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F8F8F8",
  },
  addText: {
    fontSize: 12,
    color: COLORS.mediumBrown,
    fontWeight: "bold",
    marginTop: 4,
  },

  reviewCard: {
    backgroundColor: "#F9F9F9",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  reviewerName: { fontSize: 16, fontWeight: "bold", color: COLORS.black },
  contextText: { fontSize: 12, color: COLORS.darkBrown, marginTop: 2 },
  ratingBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#EFECE9",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  ratingText: { fontSize: 12, fontWeight: "bold", color: COLORS.mediumBrown },
  reviewComment: { fontSize: 14, color: COLORS.darkBrown, marginBottom: 12 },

  replyButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    paddingVertical: 6,
  },
  replyButtonText: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.mediumBrown,
  },

  replyBox: {
    backgroundColor: "#EFECE9",
    padding: 12,
    borderRadius: 10,
    marginTop: 8,
  },
  replyTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: COLORS.mediumBrown,
    marginBottom: 2,
  },
  replyContent: { fontSize: 13, color: COLORS.darkBrown },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    padding: 24,
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 24,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.black,
    marginBottom: 16,
  },
  modalInput: {
    backgroundColor: "#F8F8F8",
    borderRadius: 12,
    padding: 16,
    height: 100,
    textAlignVertical: "top",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    marginBottom: 20,
    color: COLORS.black,
  },
  modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 12 },
  modalCancelButton: { paddingVertical: 12, paddingHorizontal: 16 },
  modalCancelText: { color: COLORS.darkBrown, fontWeight: "bold" },
  modalConfirmButton: {
    backgroundColor: COLORS.mediumBrown,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
  },
  modalConfirmText: { color: COLORS.white, fontWeight: "bold" },
});
